# Generated by Django 4.2.21 on 2025-11-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast',
            name='nutritional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='breakfast',
            name='prep_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='breakfast',
            name='servings',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lunch',
            name='nutritional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lunch',
            name='prep_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lunch',
            name='servings',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='snack',
            name='nutritional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='snack',
            name='prep_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='snack',
            name='servings',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
