# Generated by Django 4.2.23 on 2025-06-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_mealplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
